### PR TITLE
fix: switch network prompt only for metamask wallet

### LINKED ISSUE #532: fix: rainbow - wallet connect mobile
**Describe the bug**
Rainbow wallet on mobile isn't playing well with yearn.finance

**To Reproduce**
1. On a mobile device (potentially on desktop as well?) connect to yearn.finance
2. Connect a Rainbow wallet
3. open a transaction modal (depsoit or withdraw)
4. doesn't work

**Expected behavior**
Should be able to conduct transactions with rainbow wallet on mobile

**Screenshots**
image

**Environment Information**

**Additional context**

### PR DESCRIPTION
**Pull request by xgambitox**
- Fix issue with wallets that dont implement same interface as metamask for switching/adding networks. Will just prompt network change when using Metamask wallet.

Fixes #532

### CODE REVIEW

File: src/core/frameworks/blocknative/Onboard.ts [hunk 1]
```diff
@@ -139,8 +139,12 @@ export class BlocknativeWalletImpl implements Wallet {
     const { NETWORK_SETTINGS } = getConfig();
     const networkSettings = NETWORK_SETTINGS[network];
     const networkId = networkSettings.networkId;
+
     if (this.onboard) {
       this.onboard.config({ networkId });
+    }
+
+    if (this.onboard && this.name === 'MetaMask') {
```
Comment (karelianpie) [inline src/core/frameworks/blocknative/Onboard.ts:147]:
```suggestion
    if (this.onboard && this.name?.toUpperCase() === 'MetaMask'.toUpperCase()) {
```

Just in case :)

**Review by karelianpie — APPROVED** [review]
LGTM, minor nit about going with case insensitive string comparison just in case and extracting the `isMetaMask()` util function

File: src/core/frameworks/blocknative/Onboard.ts (hunk 1 above)
Comment (xgambitox) [reply src/core/frameworks/blocknative/Onboard.ts]: Refactored in https://github.com/yearn/yearn-finance-v3/pull/559/commits/9dae939b9d53fc441c227bbf8bbdfd8d2a58dfba 👍

**Review by karelianpie — APPROVED** [review]

File: src/core/frameworks/blocknative/Onboard.ts [hunk 2]
```diff
@@ -198,4 +203,8 @@ export class BlocknativeWalletImpl implements Wallet {
       return false;
     }
   }
+
+  private isMetaMask(): boolean {
+    return this.name?.toUpperCase() === 'MetaMask'.toUpperCase();
```
Comment (FiboApe) [inline src/core/frameworks/blocknative/Onboard.ts:208]: we can check for window.ethereum.isMetamask?

**Review by turtlemoji — APPROVED** [review]
