### PR TITLE
fix: portfolio wallet deposit modal vault select

### LINKED ISSUE #626: fix: portfolio wallet deposit modal
**Describe the bug**
From the portfolio page, cannot change which vault depositing into

**To Reproduce**
1. Go to portfolio page
2. Click on deposit from any token in wallet

**Expected behavior**
Should be able to change which vault being deposited or zapped into

**Screenshots**
wbtc can only go to wbtc from wallet 
image

but from other vaults I can deposit wbtc

CRV is only pointing to rocket (like many other vaults, rocket is default)
image

but from vault details on other vaults I can zap.

**Environment Information**

**Additional context**

### PR DESCRIPTION
**Pull request by edwinzhng**
## Description

* Currently, the transaction deposit modal expects the URL path to be `/wallet` when it sets the `allowVaultSelect` parameter `true`, this doesn't happen right now since the new page URL path is `/portfolio`
* I updated the code to pass in props to the modal instead of reading the path, so that this is more explicit and shouldn't happen again if we ever change the page URL path later down the road

## Related Issue

Fixes #626 

## Motivation and Context

Now users can select a vault to zap into again instead of just the default

## How Has This Been Tested?

Manually tested on portfolio wallet page with different tokens. Also tested the vault page and confirmed that functionality is still the same there (can change token but cannot change vault to deposit into).

## Screenshots (if appropriate):

Screen Shot 2022-05-03 at 5 11 08 PM

Screen Shot 2022-05-03 at 5 13 19 PM

### CODE REVIEW

File: src/client/routes/Portfolio/index.tsx [hunk 1]
```diff
@@ -141,7 +141,12 @@ export const Portfolio = () => {
     switch (action) {
       case 'invest':
         dispatch(TokensActions.setSelectedTokenAddress({ tokenAddress }));
-        dispatch(ModalsActions.openModal({ modalName: 'depositTx' }));
+        dispatch(
+          ModalsActions.openModal({
+            modalName: 'depositTx',
+            modalProps: { allowTokenSelect: false, allowVaultSelect: true },
```
Comment (karelianpie) [inline src/client/routes/Portfolio/index.tsx:147]: Just wondering if this is the only place we want `{ allowTokenSelect: false, allowVaultSelect: true }`

**Review by karelianpie — APPROVED** [review]
LGTM

File: src/client/routes/Portfolio/index.tsx (hunk 1 above)
Comment (edwinzhng) [reply src/client/routes/Portfolio/index.tsx:147]: I think so, since previously it was hard-coded to only do that on the "/wallet" path. Couldn't find anywhere else we load this modal other than the vaults page

**Comment by FoxTheSin** [comment]
possibly need to apply a different fix before this?
image

**Review by turtlemoji — APPROVED** [review]

File: src/client/routes/Portfolio/index.tsx (hunk 1 above)
Comment (karelianpie) [reply src/client/routes/Portfolio/index.tsx:147]: Nice! All good

**Review by xgambitox — APPROVED** [review]

**Comment by xgambitox** [comment]
> possibly need to apply a different fix before this? image

Yeah, this was an issue with the allowlist and not related to this fix.

Good one @edwinzhng :)
